//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestiary
    {
        public int idbeast { get; set; }
        public string name { get; set; }
        public string bio { get; set; }
        public int hp { get; set; }
        public int attack { get; set; }
        public int defense { get; set; }
        public int locationid { get; set; }
        public int beasttypeid { get; set; }
    
        public virtual BeastType BeastType { get; set; }
        public virtual Location Location { get; set; }
    }
}
