//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Character()
        {
            this.Inventory = new HashSet<Inventory>();
        }
    
        public int idchar { get; set; }
        public string playername { get; set; }
        public string charname { get; set; }
        public string charclass { get; set; }
        public int charlevel { get; set; }
        public int charhp { get; set; }
        public int charmp { get; set; }
        public int charxp { get; set; }
        public string charbio { get; set; }
        public Nullable<int> charmoney { get; set; }
        public Nullable<int> groupid { get; set; }
        public Nullable<int> strength { get; set; }
        public Nullable<int> agility { get; set; }
        public Nullable<int> chardurability { get; set; }
        public Nullable<int> intelligence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
    }
}
