//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy.DatabaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fantasyDbEntities : DbContext
    {
        public fantasyDbEntities()
            : base("name=fantasyDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeastType> BeastType { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Continent> Continent { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<NPC> NPC { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<World> World { get; set; }
        public virtual DbSet<Character> Character { get; set; }
        public virtual DbSet<Bestiary> Bestiary { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
    }
}
