//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fantasy.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class World
    {
        public int idworld { get; set; }
        public string name { get; set; }
    }
}
